travis:
  secure:
    BINSTAR_TOKEN: BloMGmHPB5+st6m64e5dvNqlloBQtBkoxsO3GrNN5iCvC/soe4hnKmvdw1g6fpQLb+di9IrXuV2nmPXEgfgBS6yPw0agQdJUjRKhunr4FUQByqf5ixCSE/MG1qPYy1S0g953pj1/2Eoc0BWNQXjJdbMtCKp/vohWJpygcESZBKcWPGexR3KYOX/StXuCnZuz0U7O9DJMeHrLzWlx5ZEe3m9BHNmuQ2YnFEza0wamrtqDY5oAwzTEhFc/RjAYaItkbq5mQSJxYClrUWEScJR94mLCpiIpIWoN04aQrQo78MTaBSbSApIe2kJRgI8E1idTblQnXeoZnQtu+/nuQIdWYXoCohd7nzt46pHUuX6ueu85pkcqgu8creU91gvePl/gIhQuK4VcFLPVVHGJiGWuFDrpbXYUbF6stqzbs05tghGzYSkpsYdS8TVE9vJPTRjnjMS9EG/V74jHuaqWHR53FM2EFG5I6s2mFsAEDNH06KmxeWpOf6do0izr6tSlKnL10VEx37bQdAPdzEUPLdexBanZROQN4U/7sriChVcZo/g6LLct4B2Hgh4ZuG7afcc39QTU7pD89SzL1ohfTbwmXwA7cHTzFC2yR0OjbsvXLGwdqlCtFh1CC5/vwbGMgeRfFvPPvztgUXC1qK594LCb2UhqB9qrDGXN+yNkgbCGsWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
